const INITIAL_PARTICIPANTS_VALUE: number = 1;
const INITIAL_COST_VALUE: number = 1;
const MAX_TIPS_ALLOWED_VALUE: number = 5;
export { INITIAL_PARTICIPANTS_VALUE, INITIAL_COST_VALUE, MAX_TIPS_ALLOWED_VALUE };