import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ErrorBoundary from "@/components/layout/ErrorBoundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hobby Explore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ErrorBoundary>
          <ReactQueryProvider>
            <Providers>{children}</Providers>
          </ReactQueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
